
services:
  - type: web
    name: sour-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: OLLAMA_API_URL
        value: http://host.docker.internal:11434/api/generate
      - key: OLLAMA_MODEL
        value: codellama
